### ISSUE TITLE
com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE explained

### ISSUE THREAD

**Issue by nferdazel** [k1m0ch1/big-brother-test#1]
According to [**this**](https://ottonova.tech/our-android-apps-permissions-explained) post, the following permission is defined by Google, along with other permission, ```com.google.android.c2dm.permission.RECEIVE```.

>Permissions name: com.google.android.c2dm.permission.RECEIVE, com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE
Protection level: Normal (Custom permission)
Both of these permissions are defined by Google. The RECEIVE is used to receive push notifications and the BIND_GET_INSTALL_REFERRER_SERVICE is used by Firebase to recognize where the app was installed from.

**Comment by k1m0ch1** [comment]
oh thanks, so `BIND_GET_INSTALL_REFERRER_SERVICE` is used by Firebase to recognize where the app was installed from.

**Comment by edge500** [comment]
> According to [**this**](https://ottonova.tech/our-android-apps-permissions-explained) post, the following permission is defined by Google, along with other permission, ```com.google.android.c2dm.permission.RECEIVE```.
> 
> >Permissions name: com.google.android.c2dm.permission.RECEIVE, com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE
> Protection level: Normal (Custom permission)
> Both of these permissions are defined by Google. The RECEIVE is used to receive push notifications and the BIND_GET_INSTALL_REFERRER_SERVICE is used by Firebase to recognize where the app was installed from.
